
# Abstract

Many data-limited stock assessments rely on survey indices for the provision of science advice. Estimates of stock size are often derived from design-based approaches, but the quantification of uncertainty around these estimates remains a challenge. Standard practice has been to use quantiles from a Student's t distribution to approximate confidence intervals, but this method sometimes produces negative values for positive quantities like biomass and abundance. As an alternate method, we propose the use of the Gamma distribution to approximate uncertainty around survey indices. This involves the translation of unbiased design-based mean and variance estimators to the shape and scale parameters for the Gamma distribution. Via simulation testing, we show that densities and confidence intervals derived from the Gamma distribution closely match densities derived from bootstrapped samples of simulated survey data. Results also indicate that the Gamma approximation offers a reasonable survey-based approach for quantifying the probability that a stock is above or below a reference level. While preliminary, these results clearly demonstrate that the Gamma distribution offers a more realistic description of the uncertainty around survey indices than the Student's t distribution.

# Introduction

A primary objective of fisheries-independent trawl surveys is to obtain indices of stock size and quantify the uncertainty around these indices. Such information plays a critical role in the assessment and management of fish stocks around the world, as they often serve as a leading indicator of trend and status [@kimura2006; @pennington1998]. Quantifying uncertainty around stock size, trends, and status is a challenging but necessary task, as fisheries management increasingly relies on such information to characterize the risk associated with alternative management options. Whenever possible, this quantification of uncertainty is done using stock assessment models, which are often calibrated using survey-based indices. However, data limitations, complex stock dynamics, and operational capacity constraints often preclude the implementation of complex stock assessment models. In these cases, the assessment of the stock tends to be based on the survey indices themselves. This may include any additional biological and ecological information that is available. Therefore, when assessments are survey-based, the quantification of uncertainty of the survey indices becomes a primary source for informing risk.

Fisheries surveys follow standardized sampling methods, and the indices derived from them are commonly design-based estimators. One of the most common survey sampling designs is the stratified-random sampling with proportional allocation, where the total sampling area is subdivided into strata, and the number of randomly allocated sampling stations within a stratum is informed by the stratum characteristics (e.g., area) and the minimum number of stations required for calculating stratum-specific statistics of the variable(s) of interest (e.g., abundance, biomass). More specifically, these statistics typically are the stratum mean and variance.

The overall mean and variance of the variable(s) of interest for the survey area are calculated from these stratum-specific indices using the general properties of the mean and variance. In the case of the mean, this translates into the straightforward idea that the overall mean represents a weighted average of the strata means, and where the weights applied are constants derived from the stratification scheme [e.g., @cochran1977]. The standard mean and variance estimators from a stratified-random sampling have the important feature that they do not depend on any assumed distribution; these estimators are valid irrespective of the underlying distribution.

Unlike the mean and variance estimators themselves, the construction of confidence intervals (CIs) for the mean often requires assuming a probability distribution. Standard CIs are typically approximated using quantiles from a Normal distribution when sample size is large, or a Student's t distribution when sample sizes are small (i.e., few degrees of freedom per stratum; [@cochran1977]). While these distributions are commonly used, both of them allow for the CIs to include negative values, something that is not realistic when analyzing strictly positive quantities like biomass and abundance [@cadigan2011]. The issue of negative values from these approximations is therefore an artifact of the distribution assumed in the construction of the CI rather than a problem with the stratified-random mean and variance estimators themselves. This justifies the application of resampling techniques like bootstrap to derive more realistic confidence intervals for stratified-random estimators.

While resampling techniques can be an effective tool to generate CIs, they do not come without their challenges. There are different ways in which resampling techniques can be implemented, and in the case of survey indices, there is little consensus on which implementation performs best. On the practical side, resampling techniques also require additional computing power and programming efforts. While these additional steps should not be a deterrent to implementing them when required, having a simpler alternative that addresses the issues linked to the normal or Student's t approximations can also be useful.

Therefore, the objective of this work is to examine the use of an alternative probability distribution to estimate CIs for fisheries surveys that does not produce negative values, and to compare these results with CIs derived from resampling techniques to evaluate its performance.

# Methods

## Selection of a probability distribution and rationale for the approach

In the Northwest Atlantic, major bottom trawl surveys follow a stratified-random sampling design with proportional allocation [e.g., @gonzalez2022; @rideout2022], and the biomass and abundance indices are calculated accordingly [e.g., @smith1981]. A cursory examination of biomass and abundance indices from these surveys not only shows that there are no negative values (naturally), but that the distributions are seldom symmetrical; long positive tails are often observed.

Given these features, the Gamma distribution emerges as a logical choice for describing these data. This distribution is always positive, and depending on the parametrization, it can be fairly symmetrical (i.e., normal-like) or have a long right tail. We propose that by changing the assumed distribution from Normal or Student’s t to Gamma, we can provide a better approximation of the confidence intervals. This approach avoids undesired features (e.g., negative lower values) and better resembles observed distributions (e.g., asymmetrical distributions with longer positive tails).

Provided data from a bottom trawl stratified-random survey, average biomass or abundance ($\hat{\mu}$) and sampling variance ($\hat{\sigma}^2$) over the stock area can be estimated using the standard random-stratified design calculations [@cochran1977; @smith1981; @smith1990]. These estimates can then be used to calculate the scale ($\hat{\theta}$) and shape ($\hat{\kappa}$) parameters of the corresponding Gamma distribution as:

\begin{equation}
\hat{\theta} = \frac{\hat{\sigma}^2}{\hat{\mu}}, ~ \text{and} ~ \hat{\kappa} = \frac{\hat{\mu}^2}{\hat{\theta}}
(\#eq:gamma)
\end{equation}

The resulting Gamma distribution is assumed to describe the data, and its quantiles are used to define the confidence intervals in the same way the Normal or Student’s t distributions are used in the standard approach.

## Aggregating estimates

Formally, this involves calculating the probability that the current index is above or below an average level $\hat{\mu}_{r}$ from a reference period $R$. Since the reference point $\hat{\mu}_{r}$ is an average of the index itself, its value cannot be perfectly known, and the uncertainty around it should also be taken into account in the estimation of the probability. Given that each individual index value included in the average has its own variance, a full consideration of the uncertainty around the average should also consider this variability. Therefore, to fully account for the uncertainty around $\hat{\mu}_{r}$, we need to combine the variances across the individual index estimates. This combined variance $\hat{\sigma}_r^2$ can be obtained by simply applying the general properties of the variance. Since $\hat{\mu}_{r}$ is effectively a linear combination of the individual indices (i.e., the sum of random variables multiplied by a constant—the inverse of sample size), the properties of the variance for a linear combination provide a way for estimating $\hat{\sigma}_r^2$. Furthermore, if we assume that the survey variances across years are independent, we can dismiss the covariances between years, and $\hat{\sigma}_r^2$ can be estimated as:

\begin{equation}
\hat{\mu}_{r} = \frac{\sum_{y=1}^{|R|} \hat{\mu}_{y}}{|R|}, ~ \text{and} ~ \hat{\sigma}_r^2 = \frac{\sum_{y=1}^{|R|} \hat{\sigma}_{y}^2}{|R|^2}
(\#eq:mean)
\end{equation}

where $\hat{\mu}_{y}$ and $\hat{\sigma}_{y}^2$ are the estimated annual mean and variance for the index in each year $y$ within the reference period $R$, and where $\left|R\right|$ is the size of the period (i.e., the number of years used to compute the average). As above, $\hat{\mu}_{r}$ and $\hat{\sigma}_r^2$ can be converted to $\hat{\theta}$ and $\hat{\kappa}$ parameters to characterize the uncertainty assuming a Gamma distribution (Equation \@ref(eq:gamma)).

## Simulation testing

While the proposed approach only involves a change in the assumption made about the distribution of the estimated mean, establishing if it is more realistic than the customary Normal/Student’s t distribution assumption requires additional analysis. To address this issue, we use simulations to test the performance of our proposed approach in two relevant scenarios:

Scenario 1. The calculation of the confidence interval for a single survey index.  

Scenario 2. The estimation of the probability that the stock is above or below some reference point.  

We explored these two scenarios by simulating a redfish-like population using the R package SimSurvey [@regular2020]. The simulated population was based on the exponential decay cohort model where parameter settings for mortality, recruitment, and growth were based on assessments of redfish in 3O and 3LN (see [Appendix A](#app:appendix-a) for details). The simulated population was distributed through an area according to the age-year-space covariance with a parabolic relationship with depth. This survey area was 300 x 300 km with 10 km$^2$ cell size and had 30 depth-based strata. We simulated stratified random sampling with a 2 m wide trawl hauled for a distance of 1.5 km. The population and survey were simulated over 20 years. The number of sets in a stratum was proportional to its area (approximately 1 set per 1000 km$^2$), and the minimum set per stratum was 2. The survey simulation was replicated five times over the same population.

To assess performance under Scenario 1, average trawlable abundance ($\hat{\mu}$) and sampling variance ($\hat{\sigma}^2$) were calculated by year (1-20) and replicate (1-5) using standard design-based estimators [@smith1981; @smith1990]. These estimates were translated to scale ($\hat{\theta}$) and shape ($\hat{\kappa}$) parameters for the Gamma distribution as described above (Equation \@ref(eq:gamma)). To compare probability densities obtained from the Gamma distribution with densities based on an empirical approach, we applied a non-parametric bootstrap to resample the observations (sets) independently within each stratum with replacement. The resampling and calculation of the mean bootstrap estimator were repeated 5000 times with the R package boot [@canty2021]. Densities from these bootstrap samples were computed for each year and survey replicate for comparison to the Gamma approximation. Finally, standard confidence intervals were computed using the t-distribution for comparison to the bootstrap and Gamma approximations.

To assess performance under Scenario 2, estimates from years 10-15 were treated as the reference period, and the average abundance and the associated variance were constructed by aggregating the annual estimates as described above (Equation \@ref(eq:mean)). These aggregate estimates were used to calculate the corresponding Gamma distribution parameters (Equation \@ref(eq:gamma)) to characterize the average abundance distribution for the reference period. Likewise, average stratified estimates of abundance across years 10-15 were bootstrapped to obtain samples for comparison with the density from the Gamma approach. Using distributions derived from the Gamma distribution and bootstrap samples, the probability that the population estimate from year 20 is lower than the reference period was computed for comparison.

This simulation can be replicated using code in [Appendix A](#app:appendix-a).

# Results and Discussion

Despite variability in central tendency caused by population dynamics and sampling noise, the shapes of the Gamma density and bootstrap samples were similar across all years and survey replicates (Figure \@ref(fig:comp-den)). This result indicates that the Gamma distribution provides a reasonable approximation of the uncertainty around the stratified estimates. A comparison of the confidence intervals derived from the Gamma distribution relative to those obtained from bootstrapping (Figure \@ref(fig:comp-ci)) further supports this conclusion. The 95% CIs from the Gamma distribution appear to be slightly larger than those from the bootstrap method, but they clearly outperform the CIs approximated using the Student’s t distribution (Figure \@ref(fig:comp-ci)) and avoid unrealistic negative values.

The Gamma approximation also appears to have comparable performance to a bootstrap approach when assessing the probability that the terminal estimate is below average levels from a reference period (Figure \@ref(fig:ref-den)). Across all five survey replicates, the mean relative difference between the probabilities computed using the two methods was less than 0.04. While these results are based on only five replicates, and hence are necessarily preliminary, they consistently indicate that the Gamma approximation offers a reasonable option for reliably quantifying the uncertainty around stock status.

Notably, previous simulations have shown that bootstrapped upper bounds are often too low (e.g., @cadigan2011). The minor differences observed here, with the Gamma distribution producing slightly higher upper bounds (Figure \@ref(fig:comp-ci)), may suggest a marginally better performance by the Gamma approach.

Further testing is warranted to accurately determine the exact coverage of the 95% confidence intervals estimated using the Gamma distribution approach. Nonetheless, these results indicate that the Gamma distribution clearly outperforms the Student’s t distribution, offering a more realistic description of the uncertainty around survey indices. Additionally, it has a generally comparable performance to resampling techniques. This suggests that using the Gamma distribution for approximating CIs is a preferable approach over the standard distributions typically used for this purpose.
